# Generated by Django 4.2.15 on 2024-08-18 14:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('hourly_price', models.IntegerField()),
                ('daily_price', models.IntegerField()),
                ('picture', models.CharField(blank=True, null=True)),
                ('size', models.IntegerField()),
                ('tv_facility', models.BooleanField()),
                ('wifi_facility', models.BooleanField()),
                ('sound_system_facility', models.BooleanField()),
                ('location', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
            ],
        ),
    ]
