# Generated by Django 4.2.15 on 2024-08-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_space', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
