# Generated by Django 4.2.15 on 2024-08-19 19:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rent_space', '0003_alter_space_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('participant_count', models.IntegerField()),
                ('price', models.IntegerField()),
                ('space_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='rent_space.space')),
            ],
        ),
    ]
