# Generated by Django 4.2.15 on 2024-08-19 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rent_space', '0004_spacereservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='spacereservation',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reserver', to=settings.AUTH_USER_MODEL, to_field='email'),
        ),
    ]
