# Generated by Django 4.2.15 on 2024-08-19 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rent_space', '0005_spacereservation_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceReservationInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('space_reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='rent_space.spacereservation')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='invitee', to=settings.AUTH_USER_MODEL, to_field='email')),
            ],
        ),
    ]
