# Generated by Django 4.2.15 on 2024-08-30 11:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rent_space', '0006_spacereservationinvitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('star', models.IntegerField()),
                ('comment', models.TextField()),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_reviews', to='rent_space.space')),
            ],
        ),
    ]
