# Generated by Django 4.2.15 on 2024-08-30 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rent_space', '0008_space_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='spacereview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_space_reviews', to=settings.AUTH_USER_MODEL, to_field='email'),
        ),
    ]
