# Generated by Django 4.2.15 on 2024-09-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_space', '0009_spacereview_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='spacereservation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('CANCELLED', 'CANCELLED'), ('REGISTERED', 'REGISTERED'), ('ATTENDED', 'ATTENDED')], default='PENDING'),
        ),
    ]
