# Generated by Django 4.2.15 on 2024-09-10 17:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('midtrans_token', models.CharField(max_length=100, unique=True)),
                ('redirect_url', models.CharField(blank=True, null=True)),
                ('gross_amount', models.IntegerField()),
                ('type', models.CharField(choices=[('EVENT', 'EVENT'), ('SPACE', 'SPACE'), ('MEMBER', 'MEMBER')], default='EVENT')),
                ('payment_status', models.CharField(default='pending', max_length=100)),
                ('fraud_status', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
