# Generated by Django 4.2.15 on 2024-08-17 19:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('picture', models.CharField(blank=True, null=True)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('WORKSHOP', 'WORKSHOP'), ('SEMINAR', 'SEMINAR')], default='WORKSHOP')),
                ('capacity', models.IntegerField()),
            ],
        ),
    ]
