# Generated by Django 4.2.15 on 2024-08-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_eventreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
