# Generated by Django 4.2.15 on 2024-08-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_event_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
