# Generated by Django 4.2.15 on 2024-08-26 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member_registration', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MemberPackage',
        ),
    ]
