# Generated by Django 4.2.15 on 2024-08-27 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member_registration', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberregistration',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='member_registration.memberpackage'),
        ),
    ]
