# Generated by Django 4.2.15 on 2024-09-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_registration', '0004_memberregistration_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberregistration',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('CANCELLED', 'CANCELLED'), ('REGISTERED', 'REGISTERED')], default='PENDING', max_length=100),
        ),
    ]
