# Generated by Django 4.2.15 on 2024-08-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='rate',
            field=models.FloatField(),
        ),
    ]
