# Generated by Django 4.2.15 on 2024-08-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_alter_tenant_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodbeverage',
            name='type',
            field=models.CharField(choices=[('FOOD', 'FOOD'), ('BEVERAGE', 'BEVERAGE'), ('OTHER', 'OTHER')], default='FOOD'),
        ),
    ]
