# Generated by Django 4.2.15 on 2024-08-27 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0006_tenantreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_review', to=settings.AUTH_USER_MODEL, to_field='email'),
        ),
    ]
