# Generated by Django 4.2.15 on 2024-09-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_alter_tenantreview_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('CANCELLED', 'CANCELLED'), ('REGISTERED', 'REGISTERED'), ('PROCESSING', 'PROCESSING'), ('DONE', 'DONE')], default='PENDING', max_length=100),
        ),
    ]
